// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";

export class Checkpoint {
  static encode(message: Checkpoint, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.epoch);

    writer.uint32(18);
    writer.bytes(message.root);
  }

  static decode(reader: Reader, length: i32): Checkpoint {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Checkpoint();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.epoch = reader.uint64();
          break;

        case 2:
          message.root = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  epoch: u64;
  root: Uint8Array;

  constructor(epoch: u64 = 0, root: Uint8Array = new Uint8Array(0)) {
    this.epoch = epoch;
    this.root = root;
  }
}
