// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";
import { AttestationData } from "./AttestationData";

export class IndexedAttestation {
  static encode(message: IndexedAttestation, writer: Writer): void {
    const attestingIndices = message.attestingIndices;
    if (attestingIndices.length !== 0) {
      for (let i: i32 = 0; i < attestingIndices.length; ++i) {
        writer.uint32(8);
        writer.uint64(attestingIndices[i]);
      }
    }

    const data = message.data;
    if (data !== null) {
      writer.uint32(18);
      writer.fork();
      AttestationData.encode(data, writer);
      writer.ldelim();
    }

    writer.uint32(26);
    writer.bytes(message.signature);
  }

  static decode(reader: Reader, length: i32): IndexedAttestation {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new IndexedAttestation();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.attestingIndices.push(reader.uint64());
          break;

        case 2:
          message.data = AttestationData.decode(reader, reader.uint32());
          break;

        case 3:
          message.signature = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  attestingIndices: Array<u64>;
  data: AttestationData | null;
  signature: Uint8Array;

  constructor(
    attestingIndices: Array<u64> = [],
    data: AttestationData | null = null,
    signature: Uint8Array = new Uint8Array(0)
  ) {
    this.attestingIndices = attestingIndices;
    this.data = data;
    this.signature = signature;
  }
}
