// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";
import { SignedBeaconBlockHeader } from "./SignedBeaconBlockHeader";

export class ProposerSlashing {
  static encode(message: ProposerSlashing, writer: Writer): void {
    const signedHeader1 = message.signedHeader1;
    if (signedHeader1 !== null) {
      writer.uint32(10);
      writer.fork();
      SignedBeaconBlockHeader.encode(signedHeader1, writer);
      writer.ldelim();
    }

    const signedHeader2 = message.signedHeader2;
    if (signedHeader2 !== null) {
      writer.uint32(18);
      writer.fork();
      SignedBeaconBlockHeader.encode(signedHeader2, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ProposerSlashing {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ProposerSlashing();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.signedHeader1 = SignedBeaconBlockHeader.decode(
            reader,
            reader.uint32()
          );
          break;

        case 2:
          message.signedHeader2 = SignedBeaconBlockHeader.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  signedHeader1: SignedBeaconBlockHeader | null;
  signedHeader2: SignedBeaconBlockHeader | null;

  constructor(
    signedHeader1: SignedBeaconBlockHeader | null = null,
    signedHeader2: SignedBeaconBlockHeader | null = null
  ) {
    this.signedHeader1 = signedHeader1;
    this.signedHeader2 = signedHeader2;
  }
}
