// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

export enum Spec {
  UNSPECIFIED = 0,
  PHASE0 = 1,
  ALTAIR = 2,
  BELLATRIX = 3,
  CAPELLA = 4,
  DENEB = 5,
}
