// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";

export class VoluntaryExit {
  static encode(message: VoluntaryExit, writer: Writer): void {
    writer.uint32(8);
    writer.uint64(message.epoch);

    writer.uint32(16);
    writer.uint64(message.validatorIndex);
  }

  static decode(reader: Reader, length: i32): VoluntaryExit {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new VoluntaryExit();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.epoch = reader.uint64();
          break;

        case 2:
          message.validatorIndex = reader.uint64();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  epoch: u64;
  validatorIndex: u64;

  constructor(epoch: u64 = 0, validatorIndex: u64 = 0) {
    this.epoch = epoch;
    this.validatorIndex = validatorIndex;
  }
}
