// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

import { Writer, Reader } from "as-proto/assembly";
import { Contract } from "./Contract";

export class Contracts {
  static encode(message: Contracts, writer: Writer): void {
    const contracts = message.contracts;
    for (let i: i32 = 0; i < contracts.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Contract.encode(contracts[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Contracts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Contracts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.contracts.push(Contract.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  contracts: Array<Contract>;

  constructor(contracts: Array<Contract> = []) {
    this.contracts = contracts;
  }
}
