// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

export enum CallType {
  UNSPECIFIED = 0,
  CALL = 1,
  CALLCODE = 2,
  DELEGATE = 3,
  STATIC = 4,
  CREATE = 5,
}
