// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v5.26.1

export enum TransactionTraceStatus {
  UNKNOWN = 0,
  SUCCEEDED = 1,
  FAILED = 2,
  REVERTED = 3,
}
